// file: GameOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package es.upm.woa.ontology;

import jade.content.onto.*;
import jade.content.schema.*;
import jade.util.leap.HashMap;
import jade.content.lang.Codec;
import jade.core.CaseInsensitiveString;

/** file: GameOntology.java
 * @author ontology bean generator
 * @version 2019/04/26, 13:38:37
 */
public class GameOntology extends jade.content.onto.Ontology  {
  //NAME
  public static final String ONTOLOGY_NAME = "game";
  // The singleton instance of this ontology
  private static ReflectiveIntrospector introspect = new ReflectiveIntrospector();
  private static Ontology theInstance = new GameOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String MOVETOCELL_TARGET="target";
    public static final String MOVETOCELL="MoveToCell";
    public static final String NOTIFYCELLDETAIL_NEWCELL="newCell";
    public static final String NOTIFYCELLDETAIL="NotifyCellDetail";
    public static final String CREATEUNIT="CreateUnit";
    public static final String CREATEBUILDING_BUILDINGTYPE="buildingType";
    public static final String CREATEBUILDING="CreateBuilding";
    public static final String NOTIFYNEWUNIT_LOCATION="location";
    public static final String NOTIFYNEWUNIT_NEWUNIT="newUnit";
    public static final String NOTIFYNEWUNIT="NotifyNewUnit";
    public static final String NOTIFYUNITPOSITION_CELL="cell";
    public static final String NOTIFYUNITPOSITION_TRIBEID="tribeId";
    public static final String NOTIFYUNITPOSITION="NotifyUnitPosition";
    public static final String RESOURCE="Resource";
    public static final String BUILDING_TYPE="type";
    public static final String BUILDING_OWNER="owner";
    public static final String BUILDING="Building";
    public static final String CELL_X="x";
    public static final String CELL_Y="y";
    public static final String CELL_CONTENT="content";
    public static final String CELL="Cell";
    public static final String EMPTY="Empty";

  /**
   * Constructor
  */
  private GameOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema emptySchema = new ConceptSchema(EMPTY);
    add(emptySchema, es.upm.woa.ontology.Empty.class);
    ConceptSchema cellSchema = new ConceptSchema(CELL);
    add(cellSchema, es.upm.woa.ontology.Cell.class);
    ConceptSchema buildingSchema = new ConceptSchema(BUILDING);
    add(buildingSchema, es.upm.woa.ontology.Building.class);
    ConceptSchema resourceSchema = new ConceptSchema(RESOURCE);
    add(resourceSchema, es.upm.woa.ontology.Resource.class);

    // adding AgentAction(s)
    AgentActionSchema notifyUnitPositionSchema = new AgentActionSchema(NOTIFYUNITPOSITION);
    add(notifyUnitPositionSchema, es.upm.woa.ontology.NotifyUnitPosition.class);
    AgentActionSchema notifyNewUnitSchema = new AgentActionSchema(NOTIFYNEWUNIT);
    add(notifyNewUnitSchema, es.upm.woa.ontology.NotifyNewUnit.class);
    AgentActionSchema createBuildingSchema = new AgentActionSchema(CREATEBUILDING);
    add(createBuildingSchema, es.upm.woa.ontology.CreateBuilding.class);
    AgentActionSchema createUnitSchema = new AgentActionSchema(CREATEUNIT);
    add(createUnitSchema, es.upm.woa.ontology.CreateUnit.class);
    AgentActionSchema notifyCellDetailSchema = new AgentActionSchema(NOTIFYCELLDETAIL);
    add(notifyCellDetailSchema, es.upm.woa.ontology.NotifyCellDetail.class);
    AgentActionSchema moveToCellSchema = new AgentActionSchema(MOVETOCELL);
    add(moveToCellSchema, es.upm.woa.ontology.MoveToCell.class);

    // adding AID(s)

    // adding Predicate(s)


    // adding fields
    cellSchema.add(CELL_CONTENT, new ConceptSchema("Concept"), ObjectSchema.OPTIONAL);
    cellSchema.add(CELL_Y, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    cellSchema.add(CELL_X, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    buildingSchema.add(BUILDING_OWNER, (ConceptSchema)getSchema(BasicOntology.AID), ObjectSchema.MANDATORY);
    buildingSchema.add(BUILDING_TYPE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    notifyUnitPositionSchema.add(NOTIFYUNITPOSITION_TRIBEID, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    notifyUnitPositionSchema.add(NOTIFYUNITPOSITION_CELL, cellSchema, ObjectSchema.MANDATORY);
    notifyNewUnitSchema.add(NOTIFYNEWUNIT_NEWUNIT, (ConceptSchema)getSchema(BasicOntology.AID), ObjectSchema.MANDATORY);
    notifyNewUnitSchema.add(NOTIFYNEWUNIT_LOCATION, cellSchema, ObjectSchema.MANDATORY);
    createBuildingSchema.add(CREATEBUILDING_BUILDINGTYPE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    notifyCellDetailSchema.add(NOTIFYCELLDETAIL_NEWCELL, cellSchema, ObjectSchema.MANDATORY);
    moveToCellSchema.add(MOVETOCELL_TARGET, cellSchema, ObjectSchema.MANDATORY);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
  }
